spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/chatApp_db
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: false

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/chat-app

  servlet:
    multipart:
      max-file-size: 50MB

application:
  file:
    uploads:
      media-output-path: ./uploads

springdoc:
  default-produces-media-type: application/json